# Generated by Django 5.2.1 on 2025-05-14 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AguaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_amostragem', models.DateField()),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('turbidez', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('oxigenio_dissolvido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qualidade', models.CharField(choices=[('boa', 'Boa'), ('moderada', 'Moderada'), ('ruim', 'Ruim'), ('desconhecida', 'Desconhecida')], default='desconhecida', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_amostragem', models.DateField()),
                ('co2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pm25', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Partículas PM2.5 (µg/m³)')),
                ('pm10', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Partículas PM10 (µg/m³)')),
                ('o3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ozônio (ppb)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('umidade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qualidade', models.CharField(choices=[('boa', 'Boa'), ('moderada', 'Moderada'), ('ruim', 'Ruim'), ('desconhecida', 'Desconhecida')], default='desconhecida', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
